<?php
namespace App\Repository;

use App\Entity\AlarmConfirm;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AlarmConfirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmConfirmRepository extends ServiceEntityRepository
{
	/**
	 * AlarmConfirmRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, AlarmConfirm::class);
    }
}
