<?php
namespace App\Repository;

use App\Entity\SchoolYearTerm;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * SchoolYearTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearTermRepository extends ServiceEntityRepository
{
	/**
	 * SchoolYearTermRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, SchoolYearTerm::class);
    }
}
