App\Entity\TimetableColumn:
    constraints:
        - App\Validator\TimetableColumn: ~
    properties:
        name:
            - NotBlank: ~
            - Length:
                  max: 30
        nameShort:
            - NotBlank: ~
            - Length:
                  max: 12
        timetableColumnRows:
            - Valid: ~