App\Entity\Timetable:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [name, schoolYear]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [nameShort, schoolYear]
        - App\Validator\Timetable: ~
    properties:
        name:
            - NotBlank: ~
            - Length:
                  max: 30
        nameShort:
            - NotBlank: ~
            - Length:
                  max: 12
        schoolYear:
            - Valid: ~
        yearGroups:
            - Valid: ~
